SELECT a.DESCRIPCION,a.ITEM_NUMBER,b.COD_ENTITY,c.DESCRIPTION,d.COD_GEO,e.DESCRIPTION 
FROM DSP_DESPACHO a INNER JOIN DSP_UNIDAD_ASIGNADA b ON a.ID_DESPACHO = b.ID_DESPACHO
INNER JOIN SAVL1120 c ON b.COD_ENTITY = c.COD_ENTITY
INNER JOIN DSP_ITINERARIO d ON a.ID_DESPACHO = d.ID_DESPACHO
INNER JOIN SAVL_G_PRIN e ON d.COD_GEO = e.COD_OBJECT_MAP

 
 
 
SELECT a.ID_DESPACHO,a.DESCRIPCION,a.ITEM_NUMBER,b.COD_ENTITY,c.DESCRIPTION,d.COD_GEO,a.FECHA_REAL_INICIO,d.FECHA_ENTREGA  
FROM DSP_DESPACHO a
INNER JOIN DSP_UNIDAD_ASIGNADA b 
ON a.ID_DESPACHO = b.ID_DESPACHO
INNER JOIN SAVL1120 c
ON b.COD_ENTITY = c.COD_ENTITY
INNER JOIN DSP_ITINERARIO d
ON a.ID_DESPACHO = d.ID_DESPACHO
WHERE  FECHA_REAL_INICIO BETWEEN '2012-10-25 00:00:00' AND '2012-10-25 23:59:59'
GROUP BY d.COD_GEO ORDER BY a.ID_DESPACHO,d.FECHA_ENTREGA ASC


SELECT b.COD_ENTITY,j.DESCRIPCION 
FROM DSP_DESPACHO a
INNER JOIN DSP_UNIDAD_ASIGNADA b 
ON a.ID_DESPACHO = b.ID_DESPACHO
INNER JOIN SAVL1120 c
ON b.COD_ENTITY = c.COD_ENTITY
INNER JOIN DSP_ITINERARIO d
ON a.ID_DESPACHO = d.ID_DESPACHO
INNER JOIN DSP_ESTATUS j
ON a.ID_ESTATUS = j.ID_ESTATUS
WHERE  FECHA_REAL_INICIO BETWEEN '2012-10-25 00:00:00' AND '2012-10-25 23:59:59'
GROUP BY d.COD_GEO ORDER BY a.ID_DESPACHO,d.FECHA_ENTREGA ASC
 
 
SELECT h.ID_ESTATUS,h.ID_DESPACHO,i.DESCRIPCION,h.COD_ENTITY FROM DSP_UNIDAD_ASIGNADA h
INNER JOIN DSP_DESPACHO i ON h.ID_DESPACHO = i.ID_DESPACHO


 